# Generated by Django 3.0.6 on 2020-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200603_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to='media/user_pics'),
        ),
    ]
