# Generated by Django 3.0.6 on 2020-06-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200603_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Event Name')),
                ('decription', models.TextField(max_length=400, verbose_name='Event Description')),
                ('created_on', models.DateField(auto_now=True)),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Event Time')),
                ('poster', models.ImageField(default='media/default_poster.png', upload_to='media/posters')),
                ('url', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Participant Name')),
                ('phone', models.CharField(max_length=14, verbose_name='Participant Mobile')),
                ('email', models.EmailField(max_length=100, verbose_name='Participant Email')),
                ('college', models.CharField(max_length=100, verbose_name='Participant College')),
                ('image', models.ImageField(default='media/default_user.png', upload_to='media/participants')),
                ('date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
