# Generated by Django 3.0.6 on 2020-06-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decription',
            new_name='description',
        ),
    ]
