# Generated by Django 3.0.6 on 2020-06-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200603_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='default_poster.png', upload_to='media/posters'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='registrations',
        ),
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='events.Registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to='media/participants'),
        ),
    ]
