# Generated by Django 3.0.6 on 2020-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200604_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='default_poster.png', upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to='participants'),
        ),
    ]
